{
    "id": 335843751,
    "sku": "00043",
    "thumbnailUrl": "https://d2j6dbq0eux0bg.cloudfront.net/images/54429245/3293184153.jpg",
    "unlimited": true,
    "inStock": true,
    "name": "Купальник раздельный \"Адель\"",
    "price": 3300,
    "priceInProductList": 3300,
    "defaultDisplayedPrice": 3300,
    "defaultDisplayedPriceFormatted": "3 300\u20bd",
    "tax": {
        "taxable": true,
        "defaultLocationIncludedTaxRate": 0,
        "enabledManualTaxes": [],
        "taxClassCode": "default"
    },
    "lowestPriceSettings": {
        "lowestPriceEnabled": false
    },
    "isShippingRequired": true,
    "hasFreeShipping": false,
    "weight": 0,
    "url": "https://bikinibomb.ru/#!/Купальник-раздельный-Адель/p/335843751",
    "autogeneratedSlug": "kupalnik-razdelny-adel-1",
    "customSlug": "",
    "created": "2021-04-11 14:45:37 +0000",
    "updated": "2024-01-14 20:46:56 +0000",
    "createTimestamp": 1618152337,
    "updateTimestamp": 1705265216,
    "productClassId": 0,
    "enabled": true,
    "options": [
        {
            "type": "RADIO",
            "name": "Цвет",
            "nameTranslated": {
                "ru": "Цвет"
            },
            "choices": [
                {
                    "text": "Черный",
                    "textTranslated": {
                        "ru": "Черный"
                    },
                    "priceModifier": 0,
                    "priceModifierType": "ABSOLUTE"
                },
                {
                    "text": "Белый",
                    "textTranslated": {
                        "ru": "Белый"
                    },
                    "priceModifier": 0,
                    "priceModifierType": "ABSOLUTE"
                },
                {
                    "text": "Розовый",
                    "textTranslated": {
                        "ru": "Розовый"
                    },
                    "priceModifier": 0,
                    "priceModifierType": "ABSOLUTE"
                }
            ],
            "defaultChoice": 0,
            "required": false
        },
        {
            "type": "RADIO",
            "name": "Размер",
            "nameTranslated": {
                "ru": "Размер"
            },
            "choices": [
                {
                    "text": "S",
                    "textTranslated": {
                        "ru": "S"
                    },
                    "priceModifier": 0,
                    "priceModifierType": "ABSOLUTE"
                },
                {
                    "text": "M",
                    "textTranslated": {
                        "ru": "M"
                    },
                    "priceModifier": 0,
                    "priceModifierType": "ABSOLUTE"
                },
                {
                    "text": "L",
                    "textTranslated": {
                        "ru": "L"
                    },
                    "priceModifier": 0,
                    "priceModifierType": "ABSOLUTE"
                }
            ],
            "defaultChoice": 0,
            "required": false
        }
    ],
    "fixedShippingRateOnly": false,
    "fixedShippingRate": 0,
    "shipping": {
        "type": "GLOBAL_METHODS",
        "methodMarkup": 0,
        "flatRate": 0,
        "disabledMethods": [],
        "enabledMethods": []
    },
    "defaultCombinationId": 0,
    "imageUrl": "https://d2j6dbq0eux0bg.cloudfront.net/images/54429245/3293184151.jpg",
    "smallThumbnailUrl": "https://d2j6dbq0eux0bg.cloudfront.net/images/54429245/3293184150.jpg",
    "hdThumbnailUrl": "https://d2j6dbq0eux0bg.cloudfront.net/images/54429245/3293184152.jpg",
    "originalImageUrl": "https://d2j6dbq0eux0bg.cloudfront.net/images/54429245/3293184149.jpg",
    "originalImage": {
        "url": "https://d2j6dbq0eux0bg.cloudfront.net/images/54429245/3293184149.jpg",
        "width": 750,
        "height": 1125
    },
    "borderInfo": {
        "dominatingColor": {
            "red": 225,
            "green": 230,
            "blue": 233,
            "alpha": 255
        },
        "homogeneity": true
    },
    "description": "<p>Купальник раздельный \"Адель\". Лиф со съемными чашками.<\/p>",
    "galleryImages": [
        {
            "id": 3,
            "url": "https://d2j6dbq0eux0bg.cloudfront.net/images/54429245/3293192008.jpg",
            "thumbnail": "https://d2j6dbq0eux0bg.cloudfront.net/images/54429245/3293192009.jpg",
            "originalImageUrl": "https://d2j6dbq0eux0bg.cloudfront.net/images/54429245/3293192008.jpg",
            "imageUrl": "https://d2j6dbq0eux0bg.cloudfront.net/images/54429245/3293192010.jpg",
            "hdThumbnailUrl": "https://d2j6dbq0eux0bg.cloudfront.net/images/54429245/3293192011.jpg",
            "thumbnailUrl": "https://d2j6dbq0eux0bg.cloudfront.net/images/54429245/3293192012.jpg",
            "smallThumbnailUrl": "https://d2j6dbq0eux0bg.cloudfront.net/images/54429245/3293192009.jpg",
            "width": 1284,
            "height": 1556,
            "orderBy": 0,
            "borderInfo": {
                "dominatingColor": {
                    "red": 79,
                    "green": 56,
                    "blue": 65,
                    "alpha": 255
                },
                "homogeneity": false
            }
        },
        {
            "id": 4,
            "url": "https://d2j6dbq0eux0bg.cloudfront.net/images/54429245/4065013539.jpg",
            "thumbnail": "https://d2j6dbq0eux0bg.cloudfront.net/images/54429245/4065013540.jpg",
            "originalImageUrl": "https://d2j6dbq0eux0bg.cloudfront.net/images/54429245/4065013539.jpg",
            "imageUrl": "https://d2j6dbq0eux0bg.cloudfront.net/images/54429245/4065013541.jpg",
            "hdThumbnailUrl": "https://d2j6dbq0eux0bg.cloudfront.net/images/54429245/4065013542.jpg",
            "thumbnailUrl": "https://d2j6dbq0eux0bg.cloudfront.net/images/54429245/4065013543.jpg",
            "smallThumbnailUrl": "https://d2j6dbq0eux0bg.cloudfront.net/images/54429245/4065013540.jpg",
            "width": 1284,
            "height": 1689,
            "orderBy": 1,
            "borderInfo": {
                "dominatingColor": {
                    "red": 213,
                    "green": 210,
                    "blue": 204,
                    "alpha": 255
                },
                "homogeneity": false
            }
        },
        {
            "id": 5,
            "url": "https://d2j6dbq0eux0bg.cloudfront.net/images/54429245/4065016800.jpg",
            "thumbnail": "https://d2j6dbq0eux0bg.cloudfront.net/images/54429245/4065016801.jpg",
            "originalImageUrl": "https://d2j6dbq0eux0bg.cloudfront.net/images/54429245/4065016800.jpg",
            "imageUrl": "https://d2j6dbq0eux0bg.cloudfront.net/images/54429245/4065016802.jpg",
            "hdThumbnailUrl": "https://d2j6dbq0eux0bg.cloudfront.net/images/54429245/4065016803.jpg",
            "thumbnailUrl": "https://d2j6dbq0eux0bg.cloudfront.net/images/54429245/4065016804.jpg",
            "smallThumbnailUrl": "https://d2j6dbq0eux0bg.cloudfront.net/images/54429245/4065016801.jpg",
            "width": 1284,
            "height": 1683,
            "orderBy": 2,
            "borderInfo": {
                "dominatingColor": {
                    "red": 185,
                    "green": 162,
                    "blue": 144,
                    "alpha": 255
                },
                "homogeneity": false
            }
        },
        {
            "id": 6,
            "url": "https://d2j6dbq0eux0bg.cloudfront.net/images/54429245/4065016795.jpg",
            "thumbnail": "https://d2j6dbq0eux0bg.cloudfront.net/images/54429245/4065016796.jpg",
            "originalImageUrl": "https://d2j6dbq0eux0bg.cloudfront.net/images/54429245/4065016795.jpg",
            "imageUrl": "https://d2j6dbq0eux0bg.cloudfront.net/images/54429245/4065016797.jpg",
            "hdThumbnailUrl": "https://d2j6dbq0eux0bg.cloudfront.net/images/54429245/4065016798.jpg",
            "thumbnailUrl": "https://d2j6dbq0eux0bg.cloudfront.net/images/54429245/4065016799.jpg",
            "smallThumbnailUrl": "https://d2j6dbq0eux0bg.cloudfront.net/images/54429245/4065016796.jpg",
            "width": 1284,
            "height": 1693,
            "orderBy": 3,
            "borderInfo": {
                "dominatingColor": {
                    "red": 192,
                    "green": 189,
                    "blue": 183,
                    "alpha": 255
                },
                "homogeneity": false
            }
        }
    ],
    "media": {
        "images": [
            {
                "id": "0",
                "isMain": true,
                "orderBy": 0,
                "image160pxUrl": "https://d2j6dbq0eux0bg.cloudfront.net/images/54429245/3293184150.jpg",
                "image400pxUrl": "https://d2j6dbq0eux0bg.cloudfront.net/images/54429245/3293184153.jpg",
                "image800pxUrl": "https://d2j6dbq0eux0bg.cloudfront.net/images/54429245/3293184152.jpg",
                "image1500pxUrl": "https://d2j6dbq0eux0bg.cloudfront.net/images/54429245/3293184151.jpg",
                "imageOriginalUrl": "https://d2j6dbq0eux0bg.cloudfront.net/images/54429245/3293184149.jpg"
            },
            {
                "id": "3",
                "isMain": false,
                "orderBy": 1,
                "image160pxUrl": "https://d2j6dbq0eux0bg.cloudfront.net/images/54429245/3293192009.jpg",
                "image400pxUrl": "https://d2j6dbq0eux0bg.cloudfront.net/images/54429245/3293192012.jpg",
                "image800pxUrl": "https://d2j6dbq0eux0bg.cloudfront.net/images/54429245/3293192011.jpg",
                "image1500pxUrl": "https://d2j6dbq0eux0bg.cloudfront.net/images/54429245/3293192010.jpg",
                "imageOriginalUrl": "https://d2j6dbq0eux0bg.cloudfront.net/images/54429245/3293192008.jpg"
            },
            {
                "id": "4",
                "isMain": false,
                "orderBy": 2,
                "image160pxUrl": "https://d2j6dbq0eux0bg.cloudfront.net/images/54429245/4065013540.jpg",
                "image400pxUrl": "https://d2j6dbq0eux0bg.cloudfront.net/images/54429245/4065013543.jpg",
                "image800pxUrl": "https://d2j6dbq0eux0bg.cloudfront.net/images/54429245/4065013542.jpg",
                "image1500pxUrl": "https://d2j6dbq0eux0bg.cloudfront.net/images/54429245/4065013541.jpg",
                "imageOriginalUrl": "https://d2j6dbq0eux0bg.cloudfront.net/images/54429245/4065013539.jpg",
                "alt": {}
            },
            {
                "id": "5",
                "isMain": false,
                "orderBy": 3,
                "image160pxUrl": "https://d2j6dbq0eux0bg.cloudfront.net/images/54429245/4065016801.jpg",
                "image400pxUrl": "https://d2j6dbq0eux0bg.cloudfront.net/images/54429245/4065016804.jpg",
                "image800pxUrl": "https://d2j6dbq0eux0bg.cloudfront.net/images/54429245/4065016803.jpg",
                "image1500pxUrl": "https://d2j6dbq0eux0bg.cloudfront.net/images/54429245/4065016802.jpg",
                "imageOriginalUrl": "https://d2j6dbq0eux0bg.cloudfront.net/images/54429245/4065016800.jpg",
                "alt": {}
            },
            {
                "id": "6",
                "isMain": false,
                "orderBy": 4,
                "image160pxUrl": "https://d2j6dbq0eux0bg.cloudfront.net/images/54429245/4065016796.jpg",
                "image400pxUrl": "https://d2j6dbq0eux0bg.cloudfront.net/images/54429245/4065016799.jpg",
                "image800pxUrl": "https://d2j6dbq0eux0bg.cloudfront.net/images/54429245/4065016798.jpg",
                "image1500pxUrl": "https://d2j6dbq0eux0bg.cloudfront.net/images/54429245/4065016797.jpg",
                "imageOriginalUrl": "https://d2j6dbq0eux0bg.cloudfront.net/images/54429245/4065016795.jpg",
                "alt": {}
            }
        ],
        "videos": []
    },
    "categoryIds": [
        96373001,
        134328613
    ],
    "categories": [
        {
            "id": 96373001,
            "enabled": true
        },
        {
            "id": 134328613,
            "enabled": true
        }
    ],
    "defaultCategoryId": 96373001,
    "seoTitle": "Купальник раздельный \"Адель\"",
    "seoDescription": "Купальник раздельный \"Адель\". Лиф со съемными чашками.",
    "attributes": [],
    "relatedProducts": {
        "productIds": [],
        "relatedCategory": {
            "enabled": false,
            "categoryId": 0,
            "productCount": 5
        }
    },
    "combinations": [],
    "volume": 0,
    "showOnFrontpage": 1,
    "isSampleProduct": false,
    "googleItemCondition": "NEW",
    "isGiftCard": false,
    "discountsAllowed": true,
    "nameYourPriceEnabled": false,
    "priceDefaultTier": 0
}